### ISSUE TITLE
Generic types should be restricted according to the GLSL specs

### ISSUE THREAD

**Issue by johnnovak** [stavenko/nim-glm#10]
This compiles, but it shouldn't.

```
var vchar = vec3('a', 'b', 'c')
var vstring = vec3("aa", "bb", "cc")
```

The use of generics should be constrained to numeric types and in some cases bools only, as per the GLSL spec:

https://www.opengl.org/wiki/Data_Type_%28GLSL%29#Basic_types

(But as far as I know the library does not support bools yet.)

On a related note, this is a port of GLM which uses GLSL conventions as closely as possible. Wouldn't it make sense to introduce GLSL datatypes then, e.g.:

```
Vec4, BVec4, IVec4, UVec4
Mat4x3, DMat4x3
Mat4, DMat4
```

And their corresponding constructor procs:

```
vec4, bvec4, ivec4, uvec4
mat4x3, dmat4x3
mat4, dmat4
```

That way the generic types `vecN[T]`, `matNxM[T]` etc. could be made private (to make instantiations like in my example above impossible) and only the specific GLSL compliant variants would be exported.

**Comment by johnnovak** [comment]
This is an example how my idea could be implemented for the `vec2` types. The internal generic type generated by the macros could be renamed to something else, like `TVec`, and should be kept private. Then the GLSL types to be exported could be added manually like this:

```
type IVec2* = TVec2[int32]
type UVec2* = TVec2[uint32]
type  Vec2* = TVec2[float32]
type DVec2* = TVec2[float64]

proc ivec2*(x, y: int32):   IVec2 = tvec2[int32]  (x, y)
proc uvec2*(x, y: uint32):  UVec2 = tvec2[uint32] (x, y)
proc  vec2*(x, y: float32):  Vec2 = tvec2[float32](x, y)
proc dvec2*(x, y: float64): DVec2 = tvec2[float64](x, y)
```

Similarly for matrices. It's not too bad to add all this manually, and we'd get precise control over what can be instantiated and what not in return (and syntactic compatibility with GLSL).

`uvec2(1, 2, 3)` is also nicer to type than `vec2[uint32](1, 2, 3)`.

**Comment by stavenko** [comment]
It does. The main thing is that I don't know if it really necessary. I thought it's a good option to use any type for this generic with only restriction, is that mathematical operation must be defined. One maybe wanting to use `type CVec3* = Vec3[Complex[Float]]` in his program and will never use this in OpenGL environment. That's the reason to name `Vec2[T]` and not `TVec2[T]`. But on the other hand people who used c++ `glm::` namespace could misuse this library. 

Let me think on this.

**Comment by johnnovak** [comment]
You're right, it would be preferable to keep the general case for non-OpenGL development contexts. After all, this doesn't have to be an exact GLM/GLSL clone...

I would still like to have GLSL style typedef in addition to the generic types (`ivec3`, `dvec3`, `uvec3` etc, as shown in my example above.). I think it would be useful if the library provided those as a convenience (not that they would be hard to define yourself...).

**Comment by krux02** [comment]
the typedefs are implemented now. They are just not exactly like you proposed them.

**Comment by krux02** [comment]
When you still want this feature, you could easily add this restriction, by restricting `T` from `Vec` and `Mat` to `SomeNumber`. That should give you exactly the restriction you want. I just didn't test anything with that.

**Comment by krux02** [comment]
the vector element type is now restricted.
