### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by mcclure** [stavenko/nim-glm#14]
Hello, this library is very useful, however I notice that there is no license on this code. Without a license in the README or a License file, we do not know for a fact we have a right to use this code. If you do not care what people do with the code you can use a permissive license such as MIT or Creative Commons Zero, but with *no* license there are many situations where people will be unable to use the code at all because it is not known to be safe.

Thanks!

**Comment by stavenko** [comment]
Good point!
Adding copyright info by commit https://github.com/stavenko/nim-glm/commit/80352072f3a68b9afc659b8d60792ba116480424

**Comment by mcclure** [comment]
Thanks! I appreciate the inclusion of MIT, because although I find your Happy Bunny license admirable, I worry it might not be compatible with GPL

**Comment by stavenko** [comment]
This project is inspired by https://github.com/g-truc/glm, which has same licenses. :)
