### ISSUE TITLE
caddr doesn't work when compiling to javascript

### ISSUE THREAD

**Issue by mcclure** [stavenko/nim-glm#16]
Say I run

```
let identity = mat4(1.0)
var example1 {.exportc.} = identity
var example2 {.exportc.} = example1.caddr
```

...well, first off, this fails in an odd way:

```
app.nim(127, 36) Error: internal error: genVarInit
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp js <file>
make: *** [Makefile:17: install/app.js] Error 1
```

(Line 127 is where the .caddr call is)

...However, second off, even if this worked, it wouldn't do what we want. The point of `caddr` is to get a value you can pass to `glUniformMatrix4fv`, which expects an in-memory array of floats. The Javascript equivalent, `gl.uniformMatrix4fv`, expects a `Float32Array`. Because of how `Mat4x4` is defined, Nim currently reifies that as an array of 4 `Float32Array`s.

**Expected behavior**: There should be some simple way to convert a `Mat4x4` to a single 16-element `Float32Array`, ideally without copying.

I'm not sure what the best way to do that would be! It seems like the two best solutions are:
1. Change `Mat4x4` to use an array of 16 floats internally instead of an array of 4 Vec4s
2. Change the js codegen in Nim so that array(4, array(4, float)) is represented as a single Float32Array of length 16??

**Comment by johnnovak** [comment]
I think the cleanest solution would be to support `caddr` for the C backend only and introduce a new method for JavaScript (e.g. `toFloat32Array`).

I don't think being able to compile the exact same code for desktop apps and the browser is a very realistic goal or expectation, therefore small backend specific irregularities like this are OK.

**Comment by stavenko** [comment]
How would this code work for those, who will decide to call `toFloat32Array` with `C` backend?

**Comment by krux02** [comment]
I am not sure, if this library is suitable for the browser in the first place.The browser does not really have different number types and this library is intended to give control over the exact size of each vector type. The vector is generic to support different number types, but javascript basically only has float64 and nothing else.

**Comment by krux02** [comment]
I know it's an old bug, but I would like to get back into the discussion. The ``caddr`` function is meant as a bridge between OpenGL functions and the glsl data types. Therefore I think it could be discussed if ``caddr`` is really the correct name for this.

Do any of you have a working ``toFloat32Array``? Since ``caddr`` is not working on the js side, I can imagine to let _that_ implementation be the _javascript_ fallback.

**Comment by krux02** [comment]
Well javascript is not the primary target, so changing the internal representation just to make javascript development easier is not something that I will do. But if there is still interest in a ``toFloat32Array`` function for the javascript backend, then I would accept the PR. But until them I am closing this.
