### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by krux02** [stavenko/nim-glm#2]
I wanted to test this glm in my project, and I can't compile, I get this error:

```
Hint: arrayUtils [Processing]
/home/arne/.nimble/pkgs/glm-0.1.0/glm/arrayUtils.nim(64, 6) Hint: 'arrayUtils.foldl(a: array[N, T], acc: S, f: proc (a: S, b: T): S{.closure.})' is declared but not used [XDeclaredButNotUsed]
/home/arne/.nimble/pkgs/glm-0.1.0/glm/vec_definitions.nim(176, 66) Error: type mismatch: got (seq[seq[string]], string)
but expected one of:
strutils.join(a: openarray[string], sep: string)
strutils.join(a: openarray[string])
> Process terminated with exit code 256
```

all I do is import. `nim install glm` works without errors

```
nimble v0.6.2 compiled at 2015-06-28 22:11:13
Nim Compiler Version 0.12.0 (2015-10-30) [Linux: amd64]
```

**Comment by stavenko** [comment]
Compiler version changed. 
I'll check this out and fix it.

**Comment by stavenko** [comment]
BTW, 
This bug caused by function repeat
I expected (And in prev version of compiler it was true):
`proc repeat[T](v:T, n:Natural):seq[T]`
But in `strutils` appeared function in v0.12.0
`proc repeat(v:string, n:Natural):string`
Which is unexpected due to absolutely different return type.

**Comment by krux02** [comment]
ok, I tested it, and it works for now, I guess you can close it now.
