### ISSUE TITLE
cannot open 'arnelib'

### ISSUE THREAD

**Issue by zacharycarter** [stavenko/nim-glm#23]
When I attempt to use the inverse proc, the following error is thrown by nim c :
Hint: mat [Processing]
/Users/zachcarter/.nimble/pkgs/glm-0.1.1/glm/mat.nim(385, 8) Error: cannot open 'arnelib'

**Comment by krux02** [comment]
There is a pull request that, including other stuff fixes this issue

https://github.com/stavenko/nim-glm/pull/24/commits/c6bf6dc862436952ba4839b202ad1504fa7c4898

Sorry for the issue, it was my fault.

**Comment by krux02** [comment]
I think this issue is fixed.
