### ISSUE TITLE
fails to compile in nim 0.17

### ISSUE THREAD

**Issue by jrenner** [stavenko/nim-glm#26]
.nimble/pkgs/glm-0.1.1/glm/vec.nim(215, 24) Error: type mismatch: got (proc (bl: typed, op: string): NimNode{.noSideEffect.})
but expected one of: 
proc head(node: NimNode): NimNode

**Comment by m-sz** [comment]
Affects me too on Arch Linux

**Comment by m-sz** [comment]
I have attached a pull request fixing this problem.
