### ISSUE TITLE
Constants

### ISSUE THREAD

**Issue by define-private-public** [stavenko/nim-glm#28]
Thanks for this port.

It would be really nice if this library had some built in constants like how `basic3d` has things like the Identity matrix built in: https://nim-lang.org/docs/basic3d.html#IDMATRIX

**Comment by define-private-public** [comment]
Something like `let unitX3 = vec3f(1, 0, 0)` would also be nice too.

**Comment by krux02** [comment]
Well you can always use this: ``mat4f(1)`` or if you prefer it the other way around ``1.mat4f``. I think this should be enough.

**Comment by krux02** [comment]
Well since this is most importantly a port of the c++ library ``glm`` and glm does not provide such functionality, I close this issue. Unless I overlooked that feature you could provide me with a link.
