### ISSUE TITLE
complete list of functions

### ISSUE THREAD

**Issue by krux02** [stavenko/nim-glm#3]
I would like to have a complete list of all functions that are actually defined in this library. wanted to pass a matrix to glLoadMatrix, and the following code did not work:

```
glLoadMatrixd(mat[0][0].addr)
```

with a type like `array[4, array[4, float64]]` it would work, but not with glm, it tells me, there is not addressable. This alone is not a bug, there must be a function that allows me to get a type to pass it to glLoadMatrixd somehow, but I couldn't find a list of functions that were in this library. The metaprogramming with macros homehow hide all the functions that are provided. I also tried `nim doc2 glm.nim` but that just had way too many errors.

**Comment by stavenko** [comment]
I wondering, which is good way to do that. Seems, like it would be nice to create docstrings to every single function  in this module. I'll figure it out.

In your case your maybe want something like

```
glLoadMatrixd(mat.addr)
```

**Comment by stavenko** [comment]
BTW. Freshly installed nim on ubuntu just gave me:

```
nim doc2 ~/.nimble/pkgs/glm-0.1.0/glm/vec.nim 
```

As a result I got good looking html. `nim v0.12.0`

**Comment by krux02** [comment]
same version, but I get lot's of errors:

```
Hint: system [Processing]
Hint: vec [Processing]
Hint: vec_definitions [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: sequtils [Processing]
Hint: macros [Processing]
lib/nim/core/macros.nim(15, 34) Error: cannot open '../doc/astspec.txt'
Hint: algorithm [Processing]
Hint: math [Processing]
Hint: times [Processing]
Hint: arrayUtils [Processing]
arrayUtils.nim(64, 6) Hint: 'arrayUtils.foldl(a: array[N, T], acc: S, f: proc (a: S, b: T): S{.closure.})' is     declared but not used [XDeclaredButNotUsed]
vec_definitions.nim(27, 23) Error: undeclared identifier: 'intVal'
vec_definitions.nim(27, 29) Error: attempting to call undeclared routine: 'intVal'
vec_definitions.nim(27, 29) Error: expression 'intVal' cannot be called
vec_definitions.nim(27, 35) Error: conversion from Error Type to int is invalid
vec_definitions.nim(28, 14) Error: undeclared identifier: 'newNimNode'
vec_definitions.nim(28, 25) Error: undeclared identifier: 'nnkStmtList'
vec_definitions.nim(28, 24) Error: attempting to call undeclared routine: 'newNimNode'
vec_definitions.nim(28, 24) Error: expression 'newNimNode' cannot be called
vec_definitions.nim(31, 20) Error: undeclared identifier: 'parseStmt'
vec_definitions.nim(31, 29) Error: attempting to call undeclared routine: 'parseStmt'
vec_definitions.nim(31, 29) Error: expression 'parseStmt' cannot be called
vec_definitions.nim(31, 15) Error: type mismatch: got (NimNode, )
but expected one of: 
system.add(x: var seq[T], y: T)
system.add(x: var string, y: char)
system.add(x: var seq[T], y: openarray[T])
system.add(x: var string, y: string)
system.add(x: var string, y: cstring)

vec_definitions.nim(38, 25) Error: attempting to call undeclared routine: 'intVal'
vec_definitions.nim(38, 25) Error: expression 'intVal' cannot be called
vec_definitions.nim(40, 24) Error: attempting to call undeclared routine: 'newNimNode'
vec_definitions.nim(40, 24) Error: expression 'newNimNode' cannot be called
vec_definitions.nim(44, 33) Error: attempting to call undeclared routine: 'parseStmt'
vec_definitions.nim(44, 33) Error: expression 'parseStmt' cannot be called
vec_definitions.nim(44, 19) Error: type mismatch: got (NimNode, )
but expected one of: 
system.add(x: var seq[T], y: T)
system.add(x: var string, y: char)
system.add(x: var seq[T], y: openarray[T])
system.add(x: var string, y: string)
system.add(x: var string, y: cstring)

vec_definitions.nim(47, 25) Error: attempting to call undeclared routine: 'intVal'
vec_definitions.nim(47, 25) Error: expression 'intVal' cannot be called
vec_definitions.nim(48, 24) Error: attempting to call undeclared routine: 'newNimNode'
vec_definitions.nim(48, 24) Error: expression 'newNimNode' cannot be called
vec_definitions.nim(50, 29) Error: attempting to call undeclared routine: 'parseStmt'
vec_definitions.nim(50, 29) Error: expression 'parseStmt' cannot be called
vec_definitions.nim(50, 15) Error: type mismatch: got (NimNode, )
```

**Comment by stavenko** [comment]
This could be linked with https://github.com/nim-lang/Nim/issues/1505

**Comment by krux02** [comment]
a fun fact is, that the file `nim /usr/share/nim/doc/astspec.txt` does exist, but `nim doc2` doesn't find it somehow. Do you know how to fix it

I would also appreciate, if you could upload the generated documentation on for example the github pages. I just tested how it works, and all you have to do is to push the generated html and an index.html file to the branch gl-pages, thats all. for convenience I just renamed the root file index.html

**Comment by krux02** [comment]
Ok, I can make it work for me, if I change the path that is hard coded into the nim libraries to the full path on my system.

I replaced `../doc/astspec.txt` with `/usr/share/nim/doc/astspec.txt` in `lib/nim/core/macros.nim` and it works for me on Arch linux.

**Comment by stavenko** [comment]
Actually, I thinking about small refactoring of very uncomfortable naming in nearest future. 
I also think about putting latest generated docs in this repo. 

So, you right, I'll do this at my soonest.

**Comment by krux02** [comment]
I also think, that maybe you should merge or take some inspiration from this project: https://github.com/yglukhov/nimsl . Even though I don't think that nim proc parameters map well to uniforms/attributes, I like the idea, that I can share code on for cpu and gpu.

**Comment by stavenko** [comment]
The best idea, I suppose, is to suggest to use `glm` for `nimsl`. I should add some functions for vectors and made small, but important refactoring. 

I think, that it's good idea to keep `glm` as small as possible. The goal is to have most convinient, yet productive and compatible library for matrix-vector manipulation.

**Comment by krux02** [comment]
yes, keep it as small as possible. But sadly your swizzling implementation is a bit of a code bloat. I like it, but it really bloats the doc2 output. I don't know how if it is possible, but maybe you can implement swizzling as a macro call, so that only those calls get implemented that are actually called.

**Comment by stavenko** [comment]
Looks, that it would be  nice to document it manually. :(

**Comment by krux02** [comment]
If you really want to have `glm` for `nimsl`, then all issues of glm need to be gone. Therefore I suggest to write lots of tests. Test all your generic functions with both float32, float64 and when supported with the integer types. Write tests for all functions, compared with the result of what c++ glm would produce. Finding bugs in an application, when the supporting matrix library is implemented wrong, can be extremely frustrating, and eat up a lot of time. The matrix library should be something I can rely on, not something where I need manually test if the functions itself work, before actually using them.
