### ISSUE TITLE
Quaternion's `rotate` proc is broken

### ISSUE THREAD

**Issue by define-private-public** [stavenko/nim-glm#30]
I to use the `rotate` proc on a `QuatF` type and the nim compiler gave me this:

```
/home/ben/.nimble/pkgs/glm-0.2.0/glm/quat.nim(282, 14) Error: type mismatch: got (Quat[system.float32], Vec[3, system.float32])
but expected one of: 
proc xyz=[N, T](v1809057: var Vec[N, T]; v2809058: Vec[3, T]): void
```

**Comment by krux02** [comment]
sorry, that doesn't look like it is a message on the rotate proc on a QuatF. can you provide a snippet of code that reproduces the error?

**Comment by define-private-public** [comment]
It was about a month ago when I was working on this, so I can't remember the exact block of code, but I think it looked like this:

```nim
import glm

var
  q = quat(vec3f(1, 0, 0), 45)

q = q.rotate(45, vec3f(1, 0, 0))  # Error here

echo(q)
```
