### ISSUE TITLE
requiring nim 0.17.3?

### ISSUE THREAD

**Issue by jackmott** [stavenko/nim-glm#35]
17.3 isn't an official release yet right, any way you can make that 0.17.2?

**Comment by dom96** [comment]
deja vu https://github.com/stavenko/nim-glm/issues/34

**Comment by krux02** [comment]
yea maybe I can change the version required to `0.17.2`

**Comment by krux02** [comment]
It seems I could just change the version, no compilation problems with the older Nim version so far. It is just that during development I only tested with the development branch of Nim and therefore I required that version.

**Comment by cpunion** [comment]
nimble clone tagged version v1.0.1, so please release a new version.

```
    Reading official package list
   Checking for glm@>= 0.1.1
 Installing glm@>= 0.1.1
    Reading official package list
Downloading https://github.com/stavenko/nim-glm using git
    Cloning latest tagged version: v1.0.1
  Verifying dependencies for glm@1.0.1
     Error: Unsatisfied dependency: nim (>= 0.17.3)
```

I just try to build https://github.com/zacharycarter/zengine.

**Comment by dom96** [comment]
You should change the required Nim version and tag a new version of this package.

**Comment by krux02** [comment]
took some time, but it's done. Tagged a new version.
