### ISSUE TITLE
Mat M N is not consistant across typedef and procs.

### ISSUE THREAD

**Issue by CodeDoes** [stavenko/nim-glm#43]
The Mat type generic is defined using M,N,T 
Sometimes for procs you use N first. This causes some confusion (for me at least). Maybe standardise this across the file atleast so that either one or the other is first.

**Comment by krux02** [comment]
I did not notice this when writing the library. This happened by accident. The idea is to use ``[N, T]`` for vector types and matrices that are just an array of vectors should use ``[M, N, T]``, where N is still the size of the vector. If I swapped M and N somewhere for the procs, I did not do it on purpose. But the library is kind of tested well (no real test cases, but I actively use it and I would notice when things break).

**Comment by krux02** [comment]
fixed it
