### ISSUE TITLE
Adding: rotate points/vectors given a quaternion

### ISSUE THREAD

**Issue by mantielero** [stavenko/nim-glm#55]
Could you add the rotation of a vector/point given a quaternion?

The function could be similar to this (I am not good at generics :o/):
```nim
proc rotate*(v:Vec3, q:Quat ):Vec3 =
  let rot = q.normalize
  let tmp = rot * quat(v[0], v[1], v[2], 0.0) * rot.conjugate
  return vec3(tmp[0], tmp[1], tmp[2])
```

So that given a rotation definition:
```nim
# Given a 90° rotation around z-axis
let HalfPi = PI * 0.5
let rot = quat(vec3(0.0, 0.0, 1.0), HalfPi)
let v = vec3(1.0,0.0,0.0)   # unit vector on x-axis
echo v.rotate(rot)
```
should show something like (unit vector on y-axis):
```
[2.220446049250313e-16  1.0  0.0]
```

**Comment by krux02** [comment]
as I once said to another feature request. This library is a close copy of GLM. it tries to port everything from GLM over as close as possible without doing anything smart here at all. So when a function like this exists in C++ GLM and I forgot to add it here, then I am willing to add it here as well. When it doesn't exist, then I am afraid, this is a close port, not a project with own design decisions (except swizzling).

**Comment by mantielero** [comment]
Understood. Thanks.
